/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS3081W auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <gtest/gtest.h>
#include "../src/event_collision.h"
#include "../src/robot.h"

/*******************************************************************************
 * Test Cases
 ******************************************************************************/
#ifdef PRIORITY1_TESTS

TEST(EventCollision, Constructor) {

  csci3081::EventCollision e2;

  // Constructor initializes to 0
  EXPECT_FALSE(e2.collided());
  EXPECT_EQ(e2.angle_of_contact(), 0);

  // Setters are working
  e2.collided(true);
  e2.angle_of_contact(45);
  EXPECT_TRUE(e2.collided());
  EXPECT_EQ(e2.angle_of_contact(), 45);
}

#endif /* COLLISION_EVENT_TEST */
