/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS3081W auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <gtest/gtest.h>
#include "../src/recharge_station.h"

#ifdef RECHARGE_STATION_TEST

static_assert(std::is_base_of<csci3081::ArenaImmobileEntity, csci3081::RechargeStation>::value,
              "FAIL: Recharge Station must be immobile");

/*******************************************************************************
 * Test Cases
 ******************************************************************************/
TEST(RechargeStation, Sanity) {
  Position pos(0, 0);
  const csci3081::Color col(255, 255, 255, 255);
  csci3081::RechargeStation rs(5.0, pos, col);

  EXPECT_EQ(rs.get_name(), "Recharge Station");
}

#endif /* RECHARGE_STATION_TEST */
